// cerr.cpp -- testing std::cerr
#include <iostream>

int main()

{
  std::cerr << "Error circumstance occured" << std::endl;
  std::cout << "Problems omitted!" << std::endl;

  return 0;
}
